window.PORTFOLIO_CONFIG = {
  githubUsername: "spxmiguel",
  repoName: "projetos-github-pages",
  siteTitle: "Projetos GitHub",
  siteDescription: ".",
  profileImageUrl: "",
  forkUrl: "https://github.com/spxmiguel/projetos-github-pages/releases/latest/download/projetos-github-pages-universal.zip",
  ctaMode: "top",
  includeForks: false,
  includeArchived: true,
  sortBy: "updated",
  encryptedToken: "",
  encryptedGroqKey: "",
  pinnedRepos: ["LootFlow","CraftServer","music-sync","video-downloader"],
  hiddenRepos: ["projetos-github-pages"],
  blogPosts: [],
};
